### ISSUE TITLE
Consider using the `term` crate instead of manually adding in console codes to strings

### ISSUE THREAD

**Issue by exicx** [Hoverth/ctow#3]
The [term](https://crates.io/crates/term) crate can handle the console codes in a more portable way than manually specifying the console codes in strings.

**Comment by Hoverth** [comment]
While this is correct, I am hesitant to add a dependency just for pretty printing a little bit of text. 

As there are ~3 total codes used, I'm more likely to just use some string constants instead.

**Comment by Hoverth** [comment]
Okay, as of commit 27ad5ce, constants are used instead of in-line strings.
